GO
SET ANSI_PADDING ON

GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'QSSJ_CBF', N'U') and NAME=N'IX_QSSJ_CBF_LXZT')
/****** Object:  Index [IX_QSSJ_CBF_LXZT]    Script Date: 2021/1/6 11:40:47 ******/
CREATE NONCLUSTERED INDEX [IX_QSSJ_CBF_LXZT] ON [QSSJ_CBF]
(
	[CBFBM] ASC,
	[CBFLX] ASC,
	[ZT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'QSSJ_CBF_JTCY', N'U') and NAME=N'IX_QSSJ_CBF_JTCY_CYXBGYR')
/****** Object:  Index [IX_QSSJ_CBF_JTCY_CYXBGYR]    Script Date: 2021/1/6 11:37:32 ******/
CREATE NONCLUSTERED INDEX [IX_QSSJ_CBF_JTCY_CYXBGYR] ON [QSSJ_CBF_JTCY]
(
	[CBFBM] ASC,
	[CYXB] ASC,
	[SFGYR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'DLXX_DK', N'U') and NAME=N'IX_DLXX_DK_DKLBMJ')
/****** Object:  Index [IX_DLXX_DK_DKLBMJ]    Script Date: 2021/1/6 11:41:51 ******/
CREATE NONCLUSTERED INDEX [IX_DLXX_DK_DKLBMJ] ON [DLXX_DK]
(
	[FBFBM] ASC,
	[DKLB] ASC,
	[SCMJM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'DLXX_DK', N'U') and NAME=N'IX_DLXX_DK_TDLYLXMJ')
/****** Object:  Index [IX_DLXX_DK_TDLYLXMJ]    Script Date: 2021/1/6 11:42:09 ******/
CREATE NONCLUSTERED INDEX [IX_DLXX_DK_TDLYLXMJ] ON [DLXX_DK]
(
	[FBFBM] ASC,
	[TDLYLX] ASC,
	[SCMJM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'DLXX_DK', N'U') and NAME=N'IX_DLXX_DK_TDYTMJ')
/****** Object:  Index [IX_DLXX_DK_TDYTMJ]    Script Date: 2021/1/6 11:42:31 ******/
CREATE NONCLUSTERED INDEX [IX_DLXX_DK_TDYTMJ] ON [DLXX_DK]
(
	[FBFBM] ASC,
	[TDYT] ASC,
	[SCMJM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'DLXX_DK', N'U') and NAME=N'IX_DLXX_DK_JBNTMJ')
/****** Object:  Index [IX_DLXX_DK_JBNTMJ]    Script Date: 2021/1/6 11:52:05 ******/
CREATE NONCLUSTERED INDEX [IX_DLXX_DK_JBNTMJ] ON [DLXX_DK]
(
	[FBFBM] ASC,
	[SFJBNT] ASC,
	[SCMJM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO