using Agro.LibCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


/*
yxm created at 2019/5/16 11:38:05
*/
namespace DataSyncTool
{
	class CreateSqliteDBUtil
	{
		/// <summary>
		/// 创建内网同步包(SQLiteDB)
		/// </summary>
		/// <param name="fileName"></param>
		public static IWorkspace CreateNwSyncDB(string fileName)
		{
			var db=WorkspaceFactory.CreateSQLiteDatabase(fileName);
			var lst = new string[]{
				DLXX_DK(),
				DLXX_DK_JZD(),
				DLXX_DK_JZX(),
				DLXX_DK_TXBGJL(),
				};
			foreach (var sql in lst)
			{
				db.ExecuteNonQuery(sql);
			}
			return db;
		}
		public static IWorkspace CreateWwSyncDB(string fileName)
		{
			var db = WorkspaceFactory.CreateSQLiteDatabase(fileName);
			var lst = new string[]{
				DLXX_DK(),
				DJ_CBJYQ_DJB(),
				DJ_CBJYQ_CBHT(),
				DJ_CBJYQ_CBF(),
				DJ_CBJYQ_CBF_JTCY(),
				DJ_CBJYQ_DKSYT(),
				DJ_CBJYQ_DKXX(),
				DJ_CBJYQ_LZDK(),
				DJ_CBJYQ_LZHT(),
				DJ_CBJYQ_QSLYZL(),
				DJ_CBJYQ_QZ(),
				DJ_CBJYQ_QZ_DYJL(),
				DJ_CBJYQ_QZBF(),
				DJ_CBJYQ_QZHF(),
				DJ_CBJYQ_WTFK(),
				DJ_CBJYQ_YDJB(),
				QSSJ_CBDKXX(),
				QSSJ_CBF(),
				QSSJ_CBF_BGJL(),
				QSSJ_CBF_JTCY(),
				QSSJ_CBHT(),
				QSSJ_CBJYQZ(),
				QSSJ_CBJYQZ_QZBF(),
				QSSJ_CBJYQZ_QZHF(),
				QSSJ_CBJYQZ_QZZX(),
				QSSJ_CBJYQZDJB(),
				QSSJ_FBF(),
				QSSJ_LZHT(),
				QSSJ_QSLYZLFJ(),
				};
			foreach (var sql in lst)
			{
				db.ExecuteNonQuery(sql);
			}
			return db;
		}

		private static string DLXX_DK()
		{
			var sql = @"CREATE TABLE DLXX_DK(
	ID VARCHAR(38) NOT NULL ,
	YSDM CHAR(6),
	FBFBM CHAR(14) NOT NULL ,
	DKBM CHAR(19) NOT NULL  PRIMARY KEY,
	DKMC NVARCHAR(50) ,
	YDKBM VARCHAR(50) ,
	SYQXZ VARCHAR(2) ,
	DKLB VARCHAR(2) ,
	TDLYLX VARCHAR(3) ,
	DLDJ VARCHAR(2) ,
	TDYT CHAR(1) ,
	SFJBNT CHAR(1) NOT NULL ,
	SCMJ NUMERIC(15, 2) NOT NULL ,
	SCMJM NUMERIC(15, 4) ,
	ELHTMJ NUMERIC(15, 4) ,
	QQMJ NUMERIC(15, 4) ,
	JDDMJ NUMERIC(15, 4) ,
	SFQQQG CHAR(1) ,
	DKDZ NVARCHAR(50) ,
	DKNZ NVARCHAR(50) ,
	DKXZ NVARCHAR(50) ,
	DKBZ NVARCHAR(50) ,
	DKBZXX NVARCHAR(254) ,
	CBFMC NVARCHAR(2000) ,
	ZJRXM NVARCHAR(100) ,
	KJZB VARCHAR(2000) ,
	ZT INT NOT NULL ,
	DJZT INT NOT NULL ,
	DYZT BOOL NOT NULL ,
	YYZT BOOL NOT NULL ,
	LZZT BOOL NOT NULL ,
	ZHXGSJ DATETIME ,
	CJSJ DATETIME ,
	DJSJ DATETIME ,
	MSSJ DATETIME ,
	SJLY INT)";
			return sql;// //db.ExecuteNonQuery(sql);
		}
		private static string DLXX_DK_JZD()//DBSQLite db)
		{
			var sql = @"CREATE TABLE DLXX_DK_JZD(
	ID VARCHAR(38) NOT NULL PRIMARY KEY,
	YSDM CHAR(6) NOT NULL,
	DKBM CHAR(19) NOT NULL,
	JZDH VARCHAR(10) NOT NULL,
	JZDLX CHAR(1) NOT NULL,
	JBLX CHAR(1),
	XZBZ NUMERIC(13, 3) NOT NULL,
	YZBZ NUMERIC(13, 3) NOT NULL)";
			////db.ExecuteNonQuery(sql);
			return sql;
		}
		private static string DLXX_DK_JZX()
		{
			var sql = @"CREATE TABLE DLXX_DK_JZX(
	ID VARCHAR(38) NOT NULL PRIMARY KEY,
	YSDM CHAR(6) NOT NULL,
	DKBM CHAR(19) NOT NULL,
	JZXH VARCHAR(10) NULL,
	JXXZ CHAR(6) ,
	JZXLB CHAR(2) ,
	JZXWZ CHAR(1) ,
	JZXSM NVARCHAR(300) ,
	PLDWQLR NVARCHAR(100) ,
	PLDWZJR NVARCHAR(100) ,
	QJZDH VARCHAR(10) ,
	ZJZDH VARCHAR(10) )";
			//db.ExecuteNonQuery(sql);
			return sql;
		}
		private static string DLXX_DK_TXBGJL()
		{
			var sql = @"CREATE TABLE DLXX_DK_TXBGJL(
	ID VARCHAR(38) NOT NULL PRIMARY KEY,
	DKID VARCHAR(38) NOT NULL,
	DKBM CHAR(19),
	YDKID VARCHAR(38) NOT NULL,
	YDKBM CHAR(19) NOT NULL,
	BGFS INT NOT NULL,
	BGYY NVARCHAR(200))";
			//db.ExecuteNonQuery(sql);
			return sql;
		}

		private static string DJ_CBJYQ_DJB()
		{
			var sql = @"CREATE TABLE DJ_CBJYQ_DJB(
	ID VARCHAR(38) NOT NULL ,
	YWH CHAR(20) ,
	QLLX INT ,
	DJLX INT ,
	DJXL INT ,
	DJYY NVARCHAR(500) NOT NULL ,
	CBJYQZBM CHAR(19) NOT NULL ,
	FBFBM CHAR(14) NOT NULL ,
	CBFBM CHAR(18) ,
	CBFMC NVARCHAR(50) ,
	CBFS CHAR(3) ,
	CBQX NVARCHAR(30) ,
	CBQXQ DATE NOT NULL ,
	CBQXZ DATE ,
	CBJYQZLSH NVARCHAR(300) ,
	YCBJYQZBH NVARCHAR(100) ,
	DKSYT NVARCHAR(2000) ,
	DBR NVARCHAR(50) ,
	DJSJ datetime2(7) ,
	QSZT INT ,
	DYZT BOOL NOT NULL ,
	YYZT BOOL NOT NULL ,
	SFYZX BOOL NOT NULL ,
	QXDM CHAR(6) NOT NULL ,
	SZDY VARCHAR(38) NOT NULL ,
	ZHXGSJ datetime2(7) ,
	FJ NVARCHAR(254) )";
			//db.ExecuteNonQuery(sql);
			return sql;
		}

		private static string DJ_CBJYQ_CBF()
		{
			var sql = @"CREATE TABLE DJ_CBJYQ_CBF(
	ID VARCHAR(38) NOT NULL   PRIMARY KEY,
	DJBID VARCHAR(38) NOT NULL ,
	CBFBM CHAR(18) NOT NULL ,
	CBFLX CHAR(1) NOT NULL ,
	CBFMC NVARCHAR(50) NOT NULL ,
	CBFZJLX CHAR(1) NOT NULL ,
	CBFZJHM NVARCHAR(20) ,
	CBFDZ NVARCHAR(100) ,
	YZBM CHAR(6) ,
	LXDH VARCHAR(20) ,
	CBFCYSL INT NOT NULL ,
	CBFDCRQ DATE ,
	CBFDCY NVARCHAR(50) ,
	CBFDCJS NVARCHAR(300) ,
	GSJS NVARCHAR(300) ,
	GSJSR NVARCHAR(50) ,
	GSSHRQ DATE ,
	GSSHR NVARCHAR(50))";
			return sql;
		}
		private static string DJ_CBJYQ_CBF_JTCY()
		{
			var sql = @"CREATE TABLE DJ_CBJYQ_CBF_JTCY(
	ID VARCHAR(38) NOT NULL   PRIMARY KEY,
	CBFBM CHAR(18) NOT NULL ,
	CBFID VARCHAR(38) NOT NULL ,
	CYXM NVARCHAR(50) NOT NULL ,
	CYXB CHAR(1) NOT NULL ,
	CYZJLX CHAR(1) ,
	CYZJHM NVARCHAR(20) ,
	CSRQ DATE ,
	YHZGX CHAR(2) ,
	CYBZ CHAR(1) ,
	SFGYR CHAR(1) ,
	CYBZSM NVARCHAR(254))";
			return sql;
		}
		private static string DJ_CBJYQ_CBHT()
		{
			var sql = @"CREATE TABLE DJ_CBJYQ_CBHT(
	ID VARCHAR(38) NOT NULL   PRIMARY KEY,
	DJBID VARCHAR(38) NOT NULL ,
	CBHTBM CHAR(19) NOT NULL ,
	YCBHTBM VARCHAR(50) ,
	FBFBM CHAR(14) NOT NULL ,
	CBFBM CHAR(18) NOT NULL ,
	CBFS CHAR(3) NOT NULL ,
	CBQXQ DATE NOT NULL ,
	CBQXZ DATE ,
	HTZMJ NUMERIC(15, 2) NOT NULL ,
	CBDKZS INT NOT NULL ,
	QDSJ DATE NOT NULL ,
	HTZMJM NUMERIC(15, 2) ,
	YHTZMJ NUMERIC(15, 2) ,
	YHTZMJM NUMERIC(15, 2))";
			return sql;
		}

		private static string DJ_CBJYQ_DKSYT()
		{
			var sql = @"CREATE TABLE DJ_CBJYQ_DKSYT(
	ID VARCHAR(38) NOT NULL PRIMARY KEY,
	DJBID VARCHAR(38) NOT NULL,
	SXH INT,
	FJ VARCHAR(254) NOT NULL)";
			//db.ExecuteNonQuery(sql);
			return sql;
		}
		private static string DJ_CBJYQ_DKXX()
		{
			var sql = @"CREATE TABLE DJ_CBJYQ_DKXX(
	ID VARCHAR(38) NOT NULL PRIMARY KEY,
	DKID VARCHAR(38) NOT NULL ,
	DJBID VARCHAR(38) NOT NULL ,
	DKBM CHAR(19) NOT NULL ,
	DKMC NVARCHAR(50) ,
	FBFBM CHAR(14) NOT NULL ,
	CBFBM CHAR(18) NOT NULL ,
	CBJYQQDFS CHAR(3) NOT NULL ,
	HTMJ NUMERIC(15, 2) ,
	CBHTBM CHAR(19) ,
	LZHTBM NVARCHAR(50) ,
	CBJYQZBM CHAR(19) ,
	YHTMJ NUMERIC(15, 2) ,
	HTMJM NUMERIC(15, 2) ,
	YHTMJM NUMERIC(15, 2) ,
	SFQQQG CHAR(1) ,
	YDKBM VARCHAR(50) ,
	SYQXZ VARCHAR(2) ,
	DKLB VARCHAR(2) ,
	TDLYLX VARCHAR(3) ,
	DLDJ VARCHAR(2) ,
	TDYT CHAR(1) ,
	SFJBNT CHAR(1) NOT NULL ,
	SCMJ NUMERIC(15, 2) NOT NULL ,
	SCMJM NUMERIC(15, 4) ,
	ELHTMJ NUMERIC(15, 4) ,
	QQMJ NUMERIC(15, 4) ,
	JDDMJ NUMERIC(15, 4) ,
	DKDZ NVARCHAR(50) ,
	DKNZ NVARCHAR(50) ,
	DKXZ NVARCHAR(50) ,
	DKBZ NVARCHAR(50) ,
	DKBZXX NVARCHAR(254) ,
	ZJRXM NVARCHAR(100) ,
	DYZT BOOL NOT NULL ,
	YYZT BOOL NOT NULL ,
	LZZT BOOL NOT NULL ,
	BZ NVARCHAR(300))";
			//db.ExecuteNonQuery(sql);
			return sql;
		}
		private static string DJ_CBJYQ_LZDK()
		{
			var sql = @"CREATE TABLE DJ_CBJYQ_LZDK(
	ID VARCHAR(38) NOT NULL PRIMARY KEY,
	DJBID VARCHAR(38) NOT NULL,
	YDJBID VARCHAR(38) NULL,
	DJBBM CHAR(19) NOT NULL,
	HTID VARCHAR(38) NOT NULL,
	HTBM CHAR(18),
	DKID VARCHAR(38) NOT NULL,
	DKBM CHAR(19) NOT NULL,
	DKMJ NUMERIC(15, 2) NOT NULL,
	DKMJM NUMERIC(15, 4))";
			//db.ExecuteNonQuery(sql);
			return sql;
		}
		private static string DJ_CBJYQ_LZHT()
		{
			var sql = @"CREATE TABLE DJ_CBJYQ_LZHT(
	ID VARCHAR(38) NOT NULL  PRIMARY KEY,
	DJBID VARCHAR(38) ,
	YDJBID VARCHAR(38) ,
	CBHTBM CHAR(19) NOT NULL ,
	LZHTBM VARCHAR(18) NOT NULL ,
	CBFBM CHAR(18) NOT NULL ,
	SRFBM CHAR(18) NOT NULL ,
	LZFS VARCHAR(3) NOT NULL ,
	LZQX NVARCHAR(10) NOT NULL ,
	LZQXKSRQ DATE NOT NULL ,
	LZQXJSRQ DATE NOT NULL ,
	LZMJ NUMERIC(15, 2) NOT NULL ,
	LZMJM NUMERIC(15, 2) ,
	LZDKS INT NOT NULL ,
	LZQTDYT CHAR(1) ,
	LZHTDYT CHAR(1) ,
	LZJGSM NVARCHAR(100) NOT NULL ,
	HTQDRQ DATE NOT NULL ,
	SZDY VARCHAR(38) NOT NULL ,
	CJYH NVARCHAR(50) ,
	CJSJ DATETIME,
	ZHXGYH NVARCHAR(50) ,
	ZHXGSJ DATETIME)";
			//db.ExecuteNonQuery(sql);
			return sql;
		}
		private static string DJ_CBJYQ_QSLYZL()
		{
			var sql = @"CREATE TABLE DJ_CBJYQ_QSLYZL(
	ID VARCHAR(38) NOT NULL PRIMARY KEY,
	FJID VARCHAR(38) NULL,
	DJBID VARCHAR(38) NOT NULL,
	CBJYQZBM CHAR(19) NOT NULL,
	ZLFJBH NVARCHAR(20) NOT NULL,
	ZLFJMC NVARCHAR(100) NOT NULL,
	ZLFJRQ DATE NOT NULL,
	FJ NVARCHAR(2000))";
			//db.ExecuteNonQuery(sql);
			return sql;
		}
		private static string DJ_CBJYQ_QZ()
		{
			var sql = @"CREATE TABLE DJ_CBJYQ_QZ(
	ID VARCHAR(38) NOT NULL PRIMARY KEY,
	[DJBID] [VARCHAR](38) NOT NULL ,
	[CBJYQZBM] [CHAR](19) NOT NULL ,
	[ZSBS] [INT] ,
	[SQSJC] [NVARCHAR](10) ,
	[BZNF] [INT] ,
	[FZJGSZDMC] [NVARCHAR](20) ,
	[NDSXH] [INT] ,
	[YZSXH] [VARCHAR](20) ,
	[CBJYQZLSH] [NVARCHAR](300) ,
	[FZJG] [NVARCHAR](50) ,
	[FZRQ] [DATE] ,
	[DYCS] [INT] ,
	[QZSFLQ] [CHAR](1) NOT NULL ,
	[QZLQRQ] [DATE] ,
	[QZLQRXM] [NVARCHAR](50) ,
	[QZLQRZJLX] [CHAR](1) ,
	[QZLQRZJHM] [NVARCHAR](20) ,
	[SFYZX] [BOOL] NOT NULL ,
	[ZXYY] [NVARCHAR](200) ,
	[ZXRQ] [DATE] ,
	[ZXSJ] [DATETIME])";
			//db.ExecuteNonQuery(sql);
			return sql;
		}
		private static string DJ_CBJYQ_QZ_DYJL()
		{
			var sql = @"CREATE TABLE DJ_CBJYQ_QZ_DYJL(
	ID VARCHAR(38) NOT NULL PRIMARY KEY,
	QZID VARCHAR(38) NOT NULL,
	DJBID VARCHAR(38) NOT NULL,
	CBJYQZBM CHAR(19) NOT NULL,
	CBJYQZLSH NVARCHAR(300),
	YZSXH VARCHAR(20),
	DYSJ DATETIME,
	DYR NVARCHAR(50))";
			//db.ExecuteNonQuery(sql);
			return sql;
		}
		private static string DJ_CBJYQ_QZBF()
		{
			var sql = @"CREATE TABLE DJ_CBJYQ_QZBF(
	ID VARCHAR(38) NOT NULL PRIMARY KEY,
	QZID VARCHAR(38) NOT NULL ,
	CBJYQZBM CHAR(19) NOT NULL ,
	QZBFYY NCHAR(200) NOT NULL ,
	BFRQ DATE ,
	QZBFLQRQ DATE ,
	QZBFLQRXM NVARCHAR(50) ,
	BFLQRZJLX CHAR(1) ,
	BFLQRZJHM NVARCHAR(20))";
			//db.ExecuteNonQuery(sql);
			return sql;
		}
		private static string DJ_CBJYQ_QZHF()
		{
			var sql = @"CREATE TABLE DJ_CBJYQ_QZHF(
	ID VARCHAR(38) NOT NULL  PRIMARY KEY,
	QZID VARCHAR(38) NOT NULL ,
	CBJYQZBM CHAR(19) NOT NULL ,
	QZHFYY NCHAR(200) NOT NULL ,
	HFRQ DATE ,
	QZHFLQRQ DATE ,
	QZHFLQRXM NVARCHAR(50) ,
	HFLQRZJLX CHAR(1) ,
	HFLQRZJHM NVARCHAR(20))";
			//db.ExecuteNonQuery(sql);
			return sql;
		}
		private static string DJ_CBJYQ_WTFK()
		{
			var sql = @"CREATE TABLE DJ_CBJYQ_WTFK(
	ID VARCHAR(38) NOT NULL  PRIMARY KEY,
	DJBID VARCHAR(38) NOT NULL ,
	CBJYQZBM CHAR(19) NOT NULL ,
	CBFMC NVARCHAR(50) NOT NULL ,
	FKRXM NVARCHAR(20) NOT NULL ,
	FKRDH VARCHAR(20) ,
	SFYWT BOOL NOT NULL ,
	WTLX INT ,
	FKNR NVARCHAR(1000) ,
	FBFBM CHAR(14) NOT NULL ,
	SZDY VARCHAR(38) NOT NULL ,
	CJSJ DATETIME NOT NULL ,
	ZHXGSJ DATETIME)";
			//db.ExecuteNonQuery(sql);
			return sql;
		}
		private static string DJ_CBJYQ_YDJB()
		{
			var sql = @"CREATE TABLE DJ_CBJYQ_YDJB(
	ID VARCHAR(38) NOT NULL  PRIMARY KEY,
	DJBID VARCHAR(38) NOT NULL ,
	YDJBID VARCHAR(38) NOT NULL ,
	SLSQID VARCHAR(38) ,
	DJLX INT ,
	DJXL INT ,
	BGLX INT ,
	BGCS NVARCHAR(254))";
			//db.ExecuteNonQuery(sql);
			return sql;
		}

		private static string QSSJ_CBDKXX()
		{
			var sql = @"CREATE TABLE QSSJ_CBDKXX(
	ID VARCHAR(38) NOT NULL   PRIMARY KEY,
	DKBM CHAR(19) NOT NULL ,
	FBFBM CHAR(14) NOT NULL ,
	CBFBM CHAR(18) NOT NULL ,
	CBJYQQDFS VARCHAR(3) NOT NULL ,
	CBHTBM CHAR(19) NOT NULL ,
	LZHTBM VARCHAR(50) ,
	CBJYQZBM CHAR(19) NOT NULL ,
	HTMJ NUMERIC(15, 2) NOT NULL ,
	YHTMJ NUMERIC(15, 2) ,
	HTMJM NUMERIC(15, 2) ,
	YHTMJM NUMERIC(15, 2) ,
	SFQQQG CHAR(1))";
			//db.ExecuteNonQuery(sql);
			return sql;
		}
		private static string QSSJ_CBF()
		{
			var sql = @"CREATE TABLE QSSJ_CBF(
	ID VARCHAR(38) NOT NULL  ,
	FBFBM CHAR(14) NOT NULL ,
	CBFBM CHAR(18) NOT NULL  PRIMARY KEY,
	CBFLX CHAR(1) NOT NULL ,
	CBFMC NVARCHAR(50) ,
	CBFZJLX CHAR(1) NOT NULL ,
	CBFZJHM NVARCHAR(20) ,
	CBFDZ NVARCHAR(100) ,
	YZBM CHAR(6) ,
	LXDH VARCHAR(20) ,
	CBFCYSL INT NOT NULL ,
	CBFDCRQ DATE ,
	CBFDCY NVARCHAR(50) ,
	CBFDCJS NVARCHAR(300) ,
	GSJS NVARCHAR(300) ,
	GSJSR NVARCHAR(50) ,
	GSSHRQ DATE ,
	GSSHR NVARCHAR(50) ,
	ZT INT NOT NULL ,
	DJZT INT NOT NULL ,
	CJSJ DATETIME(7) NOT NULL ,
	ZHXGSJ DATETIME)";
			//db.ExecuteNonQuery(sql);
			return sql;
		}
		private static string QSSJ_CBF_BGJL()
		{
			var sql = @"CREATE TABLE QSSJ_CBF_BGJL(
	ID VARCHAR(38) NOT NULL   PRIMARY KEY,
	CBFID VARCHAR(38) NOT NULL ,
	CBFBM CHAR(18) NOT NULL ,
	YCBFID VARCHAR(38) NOT NULL ,
	YCBFBM CHAR(18) NOT NULL ,
	BGFS INT)";
			//db.ExecuteNonQuery(sql);
			return sql;
		}
		private static string QSSJ_CBF_JTCY()
		{
			var sql = @"CREATE TABLE QSSJ_CBF_JTCY(
	ID VARCHAR(38) NOT NULL   PRIMARY KEY,
	CBFBM CHAR(18) NOT NULL ,
	CYXM NVARCHAR(50) NOT NULL ,
	CYXB CHAR(1) NOT NULL ,
	CYZJLX CHAR(1) ,
	CYZJHM NVARCHAR(20) ,
	CSRQ DATE ,
	YHZGX CHAR(2) ,
	CYBZ CHAR(1) ,
	SFGYR CHAR(1) ,
	CYBZSM NVARCHAR(254))";
			//db.ExecuteNonQuery(sql);
			return sql;
		}
		private static string QSSJ_CBHT()
		{
			var sql = @"CREATE TABLE QSSJ_CBHT(
	ID VARCHAR(38) NOT NULL   PRIMARY KEY,
	CBHTBM CHAR(19) NOT NULL ,
	YCBHTBM VARCHAR(50) ,
	FBFBM CHAR(14) NOT NULL ,
	CBFBM CHAR(18) NOT NULL ,
	CBFS VARCHAR(3) NOT NULL ,
	CBQXQ DATE ,
	CBQXZ DATE ,
	HTZMJ NUMERIC(15, 2) ,
	CBDKZS INT NOT NULL ,
	QDSJ DATE NOT NULL ,
	HTZMJM NUMERIC(15, 2) ,
	YHTZMJ NUMERIC(15, 2) ,
	YHTZMJM NUMERIC(15, 2) ,
	ZT INT NOT NULL ,
	DJZT INT NOT NULL ,
	CJSJ DATETIME NOT NULL ,
	ZHXGSJ DATETIME)";
			//db.ExecuteNonQuery(sql);
			return sql;
		}
		private static string QSSJ_CBJYQZ()
		{
			var sql = @"CREATE TABLE QSSJ_CBJYQZ(
	ID VARCHAR(38) NOT NULL   PRIMARY KEY,
	CBJYQZBM CHAR(19) NOT NULL ,
	FZJG NVARCHAR(50) NOT NULL ,
	FZRQ DATE NOT NULL ,
	QZSFLQ CHAR(1) NOT NULL ,
	QZLQRQ DATE ,
	QZLQRXM NVARCHAR(50) ,
	QZLQRZJLX CHAR(1) ,
	QZLQRZJHM NVARCHAR(20))";
			//db.ExecuteNonQuery(sql);
			return sql;
		}
		private static string QSSJ_CBJYQZ_QZBF()
		{
			var sql = @"CREATE TABLE QSSJ_CBJYQZ_QZBF(
	ID VARCHAR(38) NOT NULL   PRIMARY KEY,
	CBJYQZBM CHAR(19) NOT NULL ,
	QZBFYY NVARCHAR(200) NOT NULL ,
	BFRQ DATE NOT NULL ,
	QZBFLQRQ DATE NOT NULL ,
	QZBFLQRXM NVARCHAR(50) NOT NULL ,
	BFLQRZJLX CHAR(1) NOT NULL ,
	BFLQRZJHM NVARCHAR(20))";
			//db.ExecuteNonQuery(sql);
			return sql;
		}
		private static string QSSJ_CBJYQZ_QZHF()
		{
			var sql = @"CREATE TABLE QSSJ_CBJYQZ_QZHF(
	ID VARCHAR(38) NOT NULL   PRIMARY KEY,
	CBJYQZBM CHAR(19) NOT NULL ,
	QZHFYY NVARCHAR(200) NOT NULL ,
	HFRQ DATE NOT NULL ,
	QZHFLQRQ DATE NOT NULL ,
	QZHFLQRXM NVARCHAR(50) NOT NULL ,
	HFLQRZJLX CHAR(1) NOT NULL ,
	HFLQRZJHM NVARCHAR(20) NOT NULL )";
			//db.ExecuteNonQuery(sql);
			return sql;
		}
		private static string QSSJ_CBJYQZ_QZZX()
		{
			var sql = @"CREATE TABLE QSSJ_CBJYQZ_QZZX(
	ID VARCHAR(38) NOT NULL   PRIMARY KEY,
	CBJYQZBM CHAR(19) NOT NULL ,
	ZXYY NVARCHAR(200) NOT NULL ,
	ZXRQ DATE NOT NULL )";
			//db.ExecuteNonQuery(sql);
			return sql;
		}
		private static string QSSJ_CBJYQZDJB()
		{
			var sql = @"CREATE TABLE QSSJ_CBJYQZDJB(
	ID VARCHAR(38) NOT NULL   PRIMARY KEY,
	CBJYQZBM CHAR(19) NOT NULL ,
	FBFBM CHAR(14) NOT NULL ,
	CBFBM CHAR(18) NOT NULL ,
	CBFS VARCHAR(3) NOT NULL ,
	CBQX NVARCHAR(30) NOT NULL ,
	CBQXQ DATE NOT NULL ,
	CBQXZ DATE NOT NULL ,
	DKSYT NVARCHAR(2000) ,
	CBJYQZLSH NVARCHAR(300) ,
	DJBFJ NVARCHAR(300) ,
	YCBJYQZBH NVARCHAR(100) ,
	DBR NVARCHAR(50) ,
	DJSJ DATETIME)";
			//db.ExecuteNonQuery(sql);
			return sql;
		}
		private static string QSSJ_FBF()
		{
			var sql = @"CREATE TABLE QSSJ_FBF(
	ID VARCHAR(38) NOT NULL   PRIMARY KEY,
	FBFBM CHAR(14) NOT NULL ,
	FBFMC NVARCHAR(50) NOT NULL ,
	FBFFZRXM NVARCHAR(50) ,
	FZRZJLX CHAR(1) ,
	FZRZJHM NVARCHAR(30) ,
	LXDH VARCHAR(30) ,
	FBFDZ NVARCHAR(200) ,
	YZBM CHAR(6) ,
	YBM NVARCHAR(50) ,
	SZDY VARCHAR(38) NOT NULL ,
	FBFDCY NVARCHAR(50) ,
	FBFDCRQ DATE ,
	FBFDCJS NVARCHAR(300) ,
	SHR NVARCHAR(50) ,
	SHRQ DATE ,
	SHYJ NVARCHAR(300) ,
	BZ NVARCHAR(500),
	ZHXGSJ DATETIME)";
			//db.ExecuteNonQuery(sql);
			return sql;
		}
		private static string QSSJ_LZHT()
		{
			var sql = @"CREATE TABLE QSSJ_LZHT(
	ID VARCHAR(38) NOT NULL   PRIMARY KEY,
	CBHTBM CHAR(19) NOT NULL ,
	LZHTBM CHAR(18) NOT NULL ,
	CBFBM CHAR(18) NOT NULL ,
	SRFBM CHAR(18) NOT NULL ,
	LZFS VARCHAR(3) NOT NULL ,
	LZQX NVARCHAR(10) NOT NULL ,
	LZQXKSRQ DATE NOT NULL ,
	LZQXJSRQ DATE NOT NULL ,
	LZMJ NUMERIC(15, 2) NOT NULL ,
	LZMJM NUMERIC(15, 4) ,
	LZDKS INT ,
	LZQTDYT CHAR(1) ,
	LZHTDYT CHAR(1) ,
	LZJGSM NVARCHAR(100) NOT NULL ,
	HTQDRQ DATE NOT NULL )";
			return sql;
		}
		private static string QSSJ_QSLYZLFJ()
		{
			var sql = @"CREATE TABLE QSSJ_QSLYZLFJ(
	ID VARCHAR(38) NOT NULL   PRIMARY KEY,
	CBJYQZBM CHAR(19) NOT NULL ,
	ZLFJBH NVARCHAR(20) NOT NULL ,
	ZLFJMC NVARCHAR(100) NOT NULL ,
	ZLFJRQ DATE NOT NULL ,
	FJ NVARCHAR(254) NOT NULL )";
			return sql;
		}
	}
}
